#!/bin/bash
# /etc/init.d/spacekrant

### BEGIN INIT INFO
# Provides:          spacekrant
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the spacekrant
# Description:       This service is used to manage the spacekrant, starts at boot
### END INIT INFO


case "$1" in 
    start)
        echo "Starting spacekrant service"
        ( cd /home/echelon/spacekrant2/tcp && ./startSpaceService.sh > /dev/null 2>&1 ) &
        ;;
    stop)
        echo "Cleaning up spacekrant service (not really, todo)"
        ( cd /home/echelon/spacekrant2/tcp && ./stopSpaceService.sh > /dev/null 2>&1 ) &
        ;;
    *)
        echo "Usage: /etc/init.d/spacekrant start|stop"
        exit 1
        ;;
esac

exit 0

